resolver: nightly-2025-08-03

packages:
- .

extra-deps:
# ForSyDe
- forsyde-shallow-3.5.0.0

# QuickSpec
- git: https://github.com/nick8325/quickspec.git
  commit: dc011cd737f98b8a67f6051560d9fce553385905
- twee-lib-2.5 

# QuickCheck
- QuickCheck-2.14.3
